"
" TODO
" - Fold management in vsh
" - Better ranger interation?

" unlet! skip_defaults_vim
" source $VIMRUNTIME/defaults.vim

vim9s

setg langmenu=en_US.UTF-8
language message C

augroup vimrc
	au! vimrc
augroup END

runtime! vimrc.d/*.vim

filetype plugin indent on
syntax on
